# Modules
- color: "fbca04"
  description: "This issue or pull request is related to endpoint-service module."
  name: ":floppy_disk: endpoint-service"
- color: "fbca04"
  description: "This issue or pull request is related to gateway-endpoint module."
  name: ":floppy_disk: gateway-endpoint"
- color: "fbca04"
  description: "This issue or pull request is related to interface-endpoint module."
  name: ":floppy_disk: interface-endpoint"
